INSERT INTO users (user_id, name, email) VALUES(1, 'Teste 01', 'teste01@gmail.com');
INSERT INTO users (user_id, name, email) VALUES(2, 'Teste 02', 'teste02@gmail.com');
INSERT INTO users (user_id, name, email) VALUES(3, 'Teste 03', 'teste03@gmail.com');
INSERT INTO users (user_id, name, email) VALUES(4, 'Teste 04', 'teste04@gmail.com');
INSERT INTO users (user_id, name, email) VALUES(5, 'Teste 05', 'teste05@gmail.com');

INSERT INTO state (state_id, name, uf) VALUES(1, 'Acre', 'AC');
INSERT INTO state (state_id, name, uf) VALUES(2, 'Alagoas', 'AL');
INSERT INTO state (state_id, name, uf) VALUES(3, 'Amazonas', 'AM');
INSERT INTO state (state_id, name, uf) VALUES(4, 'Amapá', 'AP');
INSERT INTO state (state_id, name, uf) VALUES(5, 'Bahia', 'BA');
INSERT INTO state (state_id, name, uf) VALUES(6, 'Ceará', 'CE');
INSERT INTO state (state_id, name, uf) VALUES(7, 'Distrito Federal', 'DF');
INSERT INTO state (state_id, name, uf) VALUES(8, 'Espírito Santo', 'ES');
INSERT INTO state (state_id, name, uf) VALUES(9, 'Goiás', 'GO');
INSERT INTO state (state_id, name, uf) VALUES(10, 'Maranhão', 'MA');
INSERT INTO state (state_id, name, uf) VALUES(11, 'Minas Gerais', 'MG');
INSERT INTO state (state_id, name, uf) VALUES(12, 'Mato Grosso do Sul', 'MS');
INSERT INTO state (state_id, name, uf) VALUES(13, 'Mato Grosso', 'MT');
INSERT INTO state (state_id, name, uf) VALUES(14, 'Pará', 'PA');
INSERT INTO state (state_id, name, uf) VALUES(15, 'Paraíba', 'PB');
INSERT INTO state (state_id, name, uf) VALUES(16, 'Pernambuco', 'PE');
INSERT INTO state (state_id, name, uf) VALUES(17, 'Piauí', 'PI');
INSERT INTO state (state_id, name, uf) VALUES(18, 'Paraná', 'PR');
INSERT INTO state (state_id, name, uf) VALUES(19, 'Rio de Janeiro', 'RJ');
INSERT INTO state (state_id, name, uf) VALUES(20, 'Rio Grande do Norte', 'RN');
INSERT INTO state (state_id, name, uf) VALUES(21, 'Rondônia', 'RO');
INSERT INTO state (state_id, name, uf) VALUES(22, 'Roraima', 'RR');
INSERT INTO state (state_id, name, uf) VALUES(23, 'Rio Grande do Sul', 'RS');
INSERT INTO state (state_id, name, uf) VALUES(24, 'Santa Catarina', 'SC');
INSERT INTO state (state_id, name, uf) VALUES(25, 'Sergipe', 'SE');
INSERT INTO state (state_id, name, uf) VALUES(26, 'São Paulo', 'SP');
INSERT INTO state (state_id, name, uf) VALUES(27, 'Tocantins', 'TO');

INSERT INTO city (city_id, name, state_state_id) VALUES(1, 'Contagem', 11);
INSERT INTO city (city_id, name, state_state_id) VALUES(2, 'Belo Horizonte', 11);
INSERT INTO city (city_id, name, state_state_id) VALUES(3, 'Sarzedo', 11);
INSERT INTO city (city_id, name, state_state_id) VALUES(4, 'Ibirite', 11);
INSERT INTO city (city_id, name, state_state_id) VALUES(5, 'Bonfim', 11);
INSERT INTO city (city_id, name, state_state_id) VALUES(6, 'Moeda', 11);
INSERT INTO city (city_id, name, state_state_id) VALUES(7, 'Montes Claros', 11);
INSERT INTO city (city_id, name, state_state_id) VALUES(8, 'Salinas', 11);
INSERT INTO city (city_id, name, state_state_id) VALUES(9, 'Esmeraldas', 11);
INSERT INTO city (city_id, name, state_state_id) VALUES(10, 'Rio Acima', 11);
